version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.dev.database
      - .env.dev.web
  redis: 
    image: redis:alpine    
  database:
    image: postgres:alpine
    env_file:
      - .env.dev.database
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
