version: '3'

services:
  web:
    image: alexkudashkin/docker-rails:prod
    ports:
      - "80:3000"
    env_file:
      - .env.production.database
      - .env.production.web
  redis: 
    image: redis:alpine    
  database:
    image: postgres:alpine
    env_file:
      - .env.dev.database
    volumes:
      - db-data:/var/lib/postgresql/data
  db-migrator:
    image: alexkudashkin/docker-rails:prod
    command: ["./wait-for", "--timeout=300", "database:5432", "--", "bin/rails", "db:migrate"]
    env_file:
      - .env.production.database
      - .env.production.web
    deploy:
      restart_policy:
        condition: none

volumes:
  db-data:
